name: Build and Deploy API

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push API Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/api:latest ./api
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/api:latest
