name: Build and Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Frontend Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
